on:
  push:
    branches:
      - master
  pull_request:

name: Tests
  steps:
    - uses: actions/checkout@v2

    - name: Fetch history
      run: git fetch

    - name: Setup node
      uses: actions/setup-node@v1

    - name: Install Dependencies
      run: yarn install

    - name: Test
      run: yarn test
